### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by jwktje** [c4software/vuejs-cordova-sample#3]
Can you explain the process of adding this project structure to an existing Vue.js project? 
I'd be willing to compensate you for the trouble. I'm stuck on a hobby project and would love the help!

**Comment by c4software** [comment]
Hi,

Do you still have the problem ?

**Comment by Bezlepkin** [comment]
Is the use of such a line mandatory? Without it will not work? // Require Cordova plugin ...
